https://login.microsoftonline.com/d439e362-ecdf-4d78-8fed-86c7c639b131/oauth2/v2.0/authorize?client_id=dff5f131-dd6a-4351-b8a0-1537188e7420&scope=openid%20profile%20offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A4004%2Fauth%2Fredirect&client-request-id=cecf4f44-ead9-4e4f-b80f-81f06a3bb8fd&response_mode=form_post&response_type=code&x-client-SKU=msal.js.node&x-client-VER=1.12.0&x-client-OS=win32&x-client-CPU=x64&client_info=1&code_challenge=0DQjO4wJ0aT0joAMj4MxjD8Y9_A1ambg1IoMCDwoHwo&code_challenge_method=S256&state=eyJjc3JmVG9rZW4iOiJjZmVhMGE3YS0xMzM3LTQ4ZjItOGZkMS0wMDY2MDg1N2EyMTEiLCJyZWRpcmVjdFRvIjoiL3YyL2NhdGVnb3JpZXMvJG1ldGFkYXRhP3NhcC1sYW5ndWFnZT1FTiJ9