# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BuildJob
    displayName: Build
    pool:
      name: Azure Pipelines
    steps:
      - checkout: self

      - task: npmAuthenticate@0
        inputs:
          workingFile: .npmrc
          customEndpoint: IOTArtifacts

      - task: CmdLine@2
        displayName: Install Dependencies
        inputs:
          script: npm install -g mbt @ui5/cli

      - task: CmdLine@2
        displayName: Build
        inputs:
          script: mbt build -p=cf -s=$(Agent.BuildDirectory)/s

      - task: PublishPipelineArtifact@1
        displayName: Publish OnPrem Artifact 
        inputs:
          path: $(Agent.BuildDirectory)/s/dist
          artifactName: UI5App

      - task: PublishPipelineArtifact@1
        displayName: Publish CF Artifact
        inputs:
          path: $(Agent.BuildDirectory)/s/mta_archives/iot-errorhandler_0.0.1.mtar
          artifactName: UI5AppMTA


